version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    container_name: couclock/petrate_postgresql
    environment:
       - POSTGRES_USER=petrate
       - POSTGRES_PASSWORD=petrate
       - POSTGRES_DB=petrate
    ports:
      - "5432:5432"
      
  front:
    container_name: couclock/petrate_front
    build: ./front

  back:
    container_name: couclock/petrate_back
    build: .
    