version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    container_name: petrate_postgresql
    environment:
      - POSTGRES_USER=petrate
      - POSTGRES_PASSWORD=petrate
      - POSTGRES_DB=petrate
    ports:
      - '5432:5432'

  front:
    image: couclock/petrate_front:v2
    container_name: petrate_front
    build: ./front
    ports:
      - '80:80'
    depends_on:
      - back

  back:
    image: couclock/petrate_back:v2
    container_name: petrate_back
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
