version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    container_name: petrate_postgresql
    environment:
      - POSTGRES_USER=petrate
      - POSTGRES_PASSWORD=petrate
      - POSTGRES_DB=petrate
    ports:
      - '5432:5432'

  front:
    image: 082895264261.dkr.ecr.eu-west-1.amazonaws.com/terraform-eks-demo-front:v1
    container_name: petrate_front
    build: ./front
    ports:
      - '80:80'
    depends_on:
      - back

  back:
    image: 082895264261.dkr.ecr.eu-west-1.amazonaws.com/terraform-eks-demo-back:v1
    container_name: petrate_back
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
