apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  ports:
    - port: 8080
  selector:
    app: back
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - image: couclock/petrate_back:v1
          name: back
          ports:
            - containerPort: 8080
              name: back
