apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  ports:
    - port: 80
  selector:
    app: front
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - image: 082895264261.dkr.ecr.eu-west-1.amazonaws.com/terraform-eks-demo-front:v1
          name: front
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
              name: front
