apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - image: postgres:11-alpine
          name: postgresql
          env:
            # Use secret in real usage
            - name: POSTGRES_USER
              value: petrate
            - name: POSTGRES_PASSWORD
              value: petrate
            - name: POSTGRES_DB
              value: petrate
          ports:
            - containerPort: 5432
              name: postgresql
